Change Hex implement for int greatest that PHP_INT_MAX
Domraider/php-eth-raw-tx pull request #7
Opened 2017-12-15 11:41 UTC by NeverEndingLoopMan

2017-12-20 14:07 UTC, etienneroudeix commented on fixtures/encoder.sec.php
> +            "nonce" => BitWasp\Buffertools\Buffer::int(0),
`getBinary`

2017-12-20 14:08 UTC, etienneroudeix commented on fixtures/encoder.sec.php
> +        expect($shaed)->to->equal('8cffaff19c1efb52f6d0d985766bedef0cd361fb2a5f076144e05f234697c12a');
pas normal que ça change !

2017-12-20 14:10 UTC, etienneroudeix commented on fixtures/hex.sec.php
> +        $hex = \BitWasp\Buffertools\Buffer::int('123456789')->getHex();
on peut le passer en `int` et pas en `string` ?

2017-12-20 14:11 UTC, etienneroudeix commented on src/EthereumRawTx/Encoder/RplEncoder.php
> +            return self::encodeLength(strlen($input->getBinary()), 128) . $input->getBinary();
le cas du buffer de buffer ?

2017-12-20 14:14 UTC, etienneroudeix commented on src/EthereumRawTx/SmartContract.php
> +                if (strlen($value->getHex()) > 64) {
Dans le prototype on veut un `Buffer`

2017-12-20 14:39 UTC, NeverEndingLoopMan commented on fixtures/encoder.sec.php
> +            "nonce" => BitWasp\Buffertools\Buffer::int(0),
Pas obligatoire, en fait le RplEncode accepte soit les Buffer , soit les binaire directement
En fait tous les utint devrais rester en buffer (je vais supprimer les autre getBinary

2017-12-20 14:39 UTC, NeverEndingLoopMan commented on fixtures/encoder.sec.php
> +        expect($shaed)->to->equal('8cffaff19c1efb52f6d0d985766bedef0cd361fb2a5f076144e05f234697c12a');
Si c'est nomal erreur dans les spec, je récupérais le e2808085100000000094e9875966d7d6490592db866f815faf6fa94225a68080808080 , qui est le "bin2hex" du dessus, et pas la version binaire ... D'ou le BitWasp\Buffertools\Buffer::hex() pour récupérer sa forme binaire

2017-12-20 14:39 UTC, NeverEndingLoopMan commented on fixtures/hex.sec.php
> +        $hex = \BitWasp\Buffertools\Buffer::int('123456789')->getHex();
On peu a condition que le int ne soit pas plus grand que PHP_MAX_INT, dans le doute vaut mieux le passer en string

2017-12-20 14:39 UTC, NeverEndingLoopMan commented on src/EthereumRawTx/Encoder/RplEncoder.php
> +            return self::encodeLength(strlen($input->getBinary()), 128) . $input->getBinary();
Heu c'est possible ça ? le array de buffer oui, mais le buffer ne peut pas être un array si ?

2017-12-20 14:39 UTC, NeverEndingLoopMan commented on src/EthereumRawTx/SmartContract.php
> +                if (strlen($value->getHex()) > 64) {
Pas dans l'encodage, on transforme tout en Hex pour l'envoyer dans la blockchain (ou j'ai pas comprit ta remarque)

2017-12-20 14:54 UTC, etienneroudeix commented on fixtures/hex.sec.php
> +        $hex = \BitWasp\Buffertools\Buffer::int('123456789')->getHex();
ok

2017-12-20 15:02 UTC, etienneroudeix commented on src/EthereumRawTx/SmartContract.php
> +                if (strlen($value->getHex()) > 64) {
juste ajouter une exception alors

2017-12-20 15:57 UTC, etienneroudeix requested changes

2017-12-20 15:57 UTC, etienneroudeix commented on src/EthereumRawTx/SmartContract.php
> +                if (!is_a($value,'BitWasp\Buffertools\Buffer')) {
`is_a` => `instanceof`

2017-12-20 15:57 UTC, etienneroudeix commented on src/EthereumRawTx/Transaction.php
> +            "v" => Buffer::hex($this->v)->getBinary(),
gratouiller pour utiliser directement les buffers

2017-12-22 14:36 UTC, etienneroudeix approved these changes

2017-12-22 14:36 UTC, merged